### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [damien-lemoal/zonefs-tools#1]
I would like to point out that an identifier like “[`__ZONEFS_H__`](https://github.com/damien-lemoal/zonefs-tools/blob/7a4eedf7bb20a98fad8ac62a1c477dbcd3d42112/src/zonefs.h#L9 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by damien-lemoal** [comment]
Fixed.

**Comment by elfring** [comment]
Thanks for [your adjustment of an affected include guard](https://github.com/damien-lemoal/zonefs-tools/commit/0399ff992b12b54248676718ac327865bc359b1f "mkzonefs: Fix internal header file").
