### ISSUE TITLE
'configure: error: Couldn't find linux/blkzoned.h' occurred when compiling on 5.6.2 kernel

### ISSUE THREAD

**Issue by AlanWangGe** [damien-lemoal/zonefs-tools#2]
got this 'configure: error: Couldn't find linux/blkzoned.h' when compling on the 5.6.2 kernel

checking blkid/blkid.h usability... yes
checking blkid/blkid.h presence... yes
checking for blkid/blkid.h... yes
checking linux/blkzoned.h usability... no
checking linux/blkzoned.h presence... no
checking for linux/blkzoned.h... no
configure: error: Couldn't find linux/blkzoned.h

I find the blkzoned.h is in uapi/linux path in 5.6.2 ; so I am wondering if something should be changed for new kernel

**Comment by damien-lemoal** [comment]
My apologies for this very late reply. This error comes from the fact that the file /usr/include/linux/blkzoned.h is missing on the system you are using to compile. Several reasons for this to happen:
* Your distribution has a problem (e.g. some versions of Ubuntu have this file missing)
* Your distribution provides this file using some package that you do not have installed (unlikely)
* If you compiled and installed the kernel yourself, you did not enable zoned block device support in the kernel configuration, or you did not execute `sudo make headers_install`

This file can be obtained from the Linux kernel source code as include/uapi/linux/blkzoned.h.
