### ISSUE TITLE
Mkzonefs with aggr_cnv options, but after mount there is no cnv directory

### ISSUE THREAD

**Issue by BaronStack** [damien-lemoal/zonefs-tools#4]
## ENV
- DISK: WZS4C8T1TDSP303
- CentOS Linux release 7.4.1708 * kernel: 5.12.0
- mkzonefs-tool : version 1.5.2
## Problem
1. mkzonefs -o aggr_cnv /dev/nvme4n1
```shell
/dev/nvme4n1: 3795845120 512-byte sectors (1810 GiB)
  Host-managed device
  905 zones of 4194304 512-byte sectors (2048 MiB)
  0 conventional zones, 905 sequential zones
  0 read-only zones, 0 offline zones
Format:
  904 usable zones
  Aggregate conventional zones: enabled
  File UID: 0
  File GID: 0
  File access permissions: 640
  FS UUID: 6cfbce19-7ca7-4c81-85ac-1f900228a8d1
Resetting sequential zones
Writing super block
```
2. mount -t zonefs /dev/nvme4n1 /mnt/zonefs/
3. ls -l /mnt/zonefs
```shell
# ls /mnt/zonefs/
seq
```
There is no cnv directory, only the seq directory.
Is any suggestion to  solve the problem?

**Comment by damien-lemoal** [comment]
That would be a normal result if the drive has only one or no conventional zones. Does the drive have any conventional zones ? You can check with “blkzone report /dev/…”.

**Comment by damien-lemoal** [comment]
The drive has no conventional zones, so there will be no cnv directory with zonefs. This is normal.

**Comment by damien-lemoal** [comment]
You can use the dm-zoned device mapper but you will need another drive to emulate conventional zones. With zns, you cannot use ext4 or XFS otherwise.

**Comment by BaronStack** [comment]
Thanks for your help. I have tried the dmzadm tools.
But failed with zone capacity smaller than zone size? Why capacity affect the device mapper created.
```shell
# dmzadm --format /dev/nvme4n1 --vverbose
Module 'dm-zoned' already loaded
dm version   [ opencount flush ]   [16384] (*1)
dm versions   [ noopencount flush ]   [16384] (*1)
Found dm-zoned version 2.0.0
/dev/nvme4n1: 3795845120 512-byte sectors (1810 GiB)
  Host-managed device
  905 zones, offset 0
nvme4n1: report zones sector 0(0) zones 8191 start 0
nvme4n1: Unsupported device with zone capacity smaller than zone size
```
