### ISSUE TITLE
how can i add zonefs magic my ubuntu cant define zonefs

### ISSUE THREAD

**Issue by amirssahmadi** [damien-lemoal/zonefs-tools#7]
how can i add zonefs magic my ubuntu cant define zonefs

**Comment by damien-lemoal** [comment]
I do not understand the question... What do you mean by "Ubuntu cant define zonefs" ? Do you mean that the Ubuntu kernel does not have a precompiled zonefs kernel module ? If that is the case, then this is a feature request that should be sent to Ubuntu kernel maintainers. (I did that for Fedora a while back and now Fedora kernel ships with zonefs module precompiled).
